# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
#
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Emp-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_PATH: backend/EmployeeCrud/EmployeeCrud.csproj
  PUBLISH_PATH: ./publish

jobs:

  # ==========================================
  # BUILD JOB
  # ==========================================
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:

      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Setup .NET 8
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Build backend
      - name: Build with dotnet
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      # Publish backend
      - name: Publish backend
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PUBLISH_PATH }}

      # Upload published backend
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PUBLISH_PATH }}

  # ==========================================
  # DEPLOY JOB
  # ==========================================
  deploy:
    runs-on: windows-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:

      # Download published backend
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F3797CC8D5584F91A297A6774478313D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3177340E4A074FFDB1D1B09F3657971B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DEF80F75844446BE9CA840AD1F01C2A9 }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Emp-backend'
          slot-name: 'Production'
          package: ./publish
